name: Build iOS Tweak

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Theos
      run: |
        brew install theos
        echo "THEOS=/usr/local/opt/theos" >> $GITHUB_ENV
        echo "/usr/local/opt/theos/bin" >> $GITHUB_PATH
    
    - name: Download iOS SDK
      run: |
        cd $THEOS
        git clone --depth=1 https://github.com/theos/sdks
    
    - name: Build Tweak
      run: |
        make clean
        make package
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: BoYuCardKey
        path: packages/*.deb
